// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Available            bool     `protobuf:"varint,4,opt,name=Available,proto3" json:"Available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Record) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Record) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type Records struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Records) Reset()         { *m = Records{} }
func (m *Records) String() string { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()    {}
func (*Records) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *Records) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Records.Unmarshal(m, b)
}
func (m *Records) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Records.Marshal(b, m, deterministic)
}
func (m *Records) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Records.Merge(m, src)
}
func (m *Records) XXX_Size() int {
	return xxx_messageInfo_Records.Size(m)
}
func (m *Records) XXX_DiscardUnknown() {
	xxx_messageInfo_Records.DiscardUnknown(m)
}

var xxx_messageInfo_Records proto.InternalMessageInfo

func (m *Records) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "model.Record")
	proto.RegisterType((*Records)(nil), "model.Records")
}

func init() {
	proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d)
}

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51,
	0xca, 0xe3, 0x62, 0x0b, 0x02, 0x0b, 0x0b, 0x49, 0x71, 0x71, 0x38, 0xe7, 0x64, 0xa6, 0xe6, 0x95,
	0x78, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0x7e,
	0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12, 0x4c, 0x60, 0x19, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0xc5, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x19, 0x2c, 0x0a, 0x66, 0x0b, 0xc9, 0x70, 0x71, 0x3a, 0x96, 0x25, 0x66,
	0xe6, 0x24, 0x26, 0xe5, 0xa4, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x04, 0x21, 0x04, 0x94, 0x8c,
	0xb8, 0xd8, 0x21, 0xf6, 0x15, 0x0b, 0xa9, 0xc3, 0x99, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46,
	0xbc, 0x7a, 0x60, 0x37, 0xe9, 0x41, 0x44, 0x83, 0x60, 0xb2, 0x49, 0x6c, 0x60, 0x17, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x47, 0xfa, 0x5b, 0xc1, 0x00, 0x00, 0x00,
}
