// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestGetContacts struct {
	ContactNumber        string   `protobuf:"bytes,1,opt,name=ContactNumber,proto3" json:"ContactNumber,omitempty"`
	ContactName          string   `protobuf:"bytes,2,opt,name=ContactName,proto3" json:"ContactName,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetContacts) Reset()         { *m = RequestGetContacts{} }
func (m *RequestGetContacts) String() string { return proto.CompactTextString(m) }
func (*RequestGetContacts) ProtoMessage()    {}
func (*RequestGetContacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *RequestGetContacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetContacts.Unmarshal(m, b)
}
func (m *RequestGetContacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetContacts.Marshal(b, m, deterministic)
}
func (m *RequestGetContacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetContacts.Merge(m, src)
}
func (m *RequestGetContacts) XXX_Size() int {
	return xxx_messageInfo_RequestGetContacts.Size(m)
}
func (m *RequestGetContacts) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetContacts.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetContacts proto.InternalMessageInfo

func (m *RequestGetContacts) GetContactNumber() string {
	if m != nil {
		return m.ContactNumber
	}
	return ""
}

func (m *RequestGetContacts) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *RequestGetContacts) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type RequestUploadContacts struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUploadContacts) Reset()         { *m = RequestUploadContacts{} }
func (m *RequestUploadContacts) String() string { return proto.CompactTextString(m) }
func (*RequestUploadContacts) ProtoMessage()    {}
func (*RequestUploadContacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *RequestUploadContacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUploadContacts.Unmarshal(m, b)
}
func (m *RequestUploadContacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUploadContacts.Marshal(b, m, deterministic)
}
func (m *RequestUploadContacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUploadContacts.Merge(m, src)
}
func (m *RequestUploadContacts) XXX_Size() int {
	return xxx_messageInfo_RequestUploadContacts.Size(m)
}
func (m *RequestUploadContacts) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUploadContacts.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUploadContacts proto.InternalMessageInfo

func (m *RequestUploadContacts) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RequestUploadContacts) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestGetContacts)(nil), "request.RequestGetContacts")
	proto.RegisterType((*RequestUploadContacts)(nil), "request.RequestUploadContacts")
}

func init() {
	proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe)
}

var fileDescriptor_7f73548e33e655fe = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x2a, 0xb8,
	0x84, 0x82, 0x20, 0x4c, 0xf7, 0xd4, 0x12, 0xe7, 0xfc, 0xbc, 0x92, 0xc4, 0xe4, 0x92, 0x62, 0x21,
	0x15, 0x2e, 0x5e, 0x28, 0xdb, 0xaf, 0x34, 0x37, 0x29, 0xb5, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0x55, 0x50, 0x48, 0x81, 0x8b, 0x1b, 0x26, 0x90, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x56,
	0x83, 0x2c, 0x24, 0x24, 0xc5, 0xc5, 0xe1, 0x9c, 0x93, 0x99, 0x9a, 0x57, 0xe2, 0x99, 0x22, 0xc1,
	0x0c, 0x96, 0x86, 0xf3, 0x95, 0x5c, 0xb9, 0x44, 0xa1, 0x36, 0x87, 0x16, 0xe4, 0xe4, 0x27, 0xa6,
	0xc0, 0x2d, 0x17, 0xe0, 0x62, 0x0e, 0x2d, 0xca, 0x81, 0x5a, 0x09, 0x62, 0xa2, 0x18, 0xc3, 0x84,
	0x6a, 0x4c, 0x12, 0x1b, 0xd8, 0x43, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x6f, 0x02,
	0x66, 0xe1, 0x00, 0x00, 0x00,
}
