// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestCustomQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCustomQuery) Reset()         { *m = RequestCustomQuery{} }
func (m *RequestCustomQuery) String() string { return proto.CompactTextString(m) }
func (*RequestCustomQuery) ProtoMessage()    {}
func (*RequestCustomQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{0}
}

func (m *RequestCustomQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCustomQuery.Unmarshal(m, b)
}
func (m *RequestCustomQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCustomQuery.Marshal(b, m, deterministic)
}
func (m *RequestCustomQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCustomQuery.Merge(m, src)
}
func (m *RequestCustomQuery) XXX_Size() int {
	return xxx_messageInfo_RequestCustomQuery.Size(m)
}
func (m *RequestCustomQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCustomQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCustomQuery proto.InternalMessageInfo

func (m *RequestCustomQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestCustomQuery)(nil), "request.RequestCustomQuery")
}

func init() {
	proto.RegisterFile("util.proto", fileDescriptor_170ba741606d8a4c)
}

var fileDescriptor_170ba741606d8a4c = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xc9, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51,
	0xd2, 0xe2, 0x12, 0x0a, 0x82, 0x30, 0x9d, 0x4b, 0x8b, 0x4b, 0xf2, 0x73, 0x03, 0x4b, 0x53, 0x8b,
	0x2a, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0x0c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x27,
	0x89, 0x0d, 0xac, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x67, 0x65, 0x56, 0x49, 0x00,
	0x00, 0x00,
}
